// --- AVATAR TYPES ---
export type AvatarGender = 'Male' | 'Female';
export type AvatarSkin = 'Light' | 'Medium-Light' | 'Medium' | 'Medium-Dark' | 'Dark';
export type AvatarHairColor = 'Brown' | 'Black' | 'Blonde' | 'Red' | 'Grey' | 'White' | 'Blue' | 'Pink';
export type AvatarHairStyle = 'Short' | 'Long' | 'Curly' | 'Straight' | 'Bald' | 'Ponytail' | 'Messy' | 'Wavy';
export type AvatarEyeColor = 'Brown' | 'Blue' | 'Green' | 'Hazel' | 'Grey';

export type AvatarGlasses = 'None' | 'Reading Glasses' | 'Sunglasses' | 'Round Glasses' | 'Square Glasses';
export type AvatarHeadwear = 'None' | 'Cap' | 'Beanie' | 'Headphones' | 'Bandana' | 'Hat';

export type AvatarClothingColor = 'Black' | 'White' | 'Red' | 'Blue' | 'Green' | 'Yellow' | 'Pink' | 'Grey' | 'Beige' | 'Navy' | 'Burgundy';
export type AvatarTopType = 'T-Shirt' | 'Hoodie' | 'Shirt' | 'Suit Jacket' | 'Sweater' | 'Tank Top' | 'Vest' | 'Polo' | 'Lab Coat';
export type AvatarBottomType = 'Jeans' | 'Shorts' | 'Trousers' | 'Skirt' | 'Joggers' | 'Leggings';
export type AvatarShoesType = 'Sneakers' | 'Boots' | 'Formal Shoes' | 'Sandals' | 'Loafers';

export type AvatarExpression = 'happy' | 'sad' | 'sleepy' | 'sleeping';

export interface AvatarConfig {
    gender: AvatarGender;
    skin: AvatarSkin;
    hairColor: AvatarHairColor;
    hairStyle: AvatarHairStyle;
    eyeColor: AvatarEyeColor;
    glasses: AvatarGlasses;
    headwear: AvatarHeadwear;
    topType: AvatarTopType;
    topColor: AvatarClothingColor;
    bottomType: AvatarBottomType;
    bottomColor: AvatarClothingColor;
    shoesType: AvatarShoesType;
    shoesColor: AvatarClothingColor;
}

// --- APP TYPES ---

export type ActivityType = 'work' | 'rest' | 'habit' | 'exercise' | 'social' | 'health' | 'other';

export interface TimeBlock {
  id: string;
  title: string;
  startTime: string; // HH:mm
  endTime: string;   // HH:mm
  type: ActivityType;
  isCompleted: boolean; // For "Reality" tracking
  notes?: string;
}

export interface DayPlan {
  date: string;
  plannedBlocks: TimeBlock[];
  actualBlocks: TimeBlock[]; // For Plan vs Reality comparison
  score: number; // calculated based on completion
}

export interface Habit {
  id: string;
  title: string;
  frequency: 'daily' | 'weekly';
  streak: number;
  completedDates: string[]; // ISO date strings (YYYY-MM-DD)
  category: 'health' | 'productivity' | 'mindfulness';
  aiTip?: string; // AI generated tip
}

export interface InboxMessage {
  id: string;
  sender: string;
  subject: string;
  body: string;
  date: string;
  read: boolean;
  type: 'general' | 'achievement' | 'welcome';
}

export interface UserPreferences {
    theme: 'light' | 'dark' | 'system';
    language: 'sk' | 'en';
    notificationsEmail: boolean;
    notificationsPush: boolean;
    bio?: string; // E.g. "Morning person"
}

export interface UserProfile {
  name: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  dateOfBirth?: string;
  goals: string[]; // e.g., "Improve sleep", "Learn React"
  
  // Replaced string 'preferences' with object, kept string as fallback or migrated property if needed
  preferences: string | UserPreferences; 
  
  avatarUrl: string | null; // Generated by Gemini
  avatarConfig?: AvatarConfig; // Saved attributes for dynamic regeneration
  
  // Gamification Stats
  twinLevel: number; // Gamification level
  levelTitle?: string; // e.g. "Novice Twin"
  xp: number; // Current XP
  xpToNextLevel: number; // This is now dynamic based on level curve
  energy: number; // Daily energy level (0-100)
  
  // Anti-Cheat & Daily Tracking
  lastActivityDate: string; // YYYY-MM-DD
  dailyHabitCount: number; // Limit: 10
  dailyBlockCount: number; // Limit: 12
  dailyPlanCreated: boolean; // Limit: 1
  
  messages: InboxMessage[];
}

export interface SearchResult {
  title: string;
  uri: string;
}

export enum AppView {
  DASHBOARD = 'dashboard',
  PLANNER = 'planner',
  HABITS = 'habits',
  PROFILE = 'profile',
  INBOX = 'inbox',
  SETTINGS = 'settings' // New View
}